### ISSUE TITLE
no Keys.js in package

### ISSUE THREAD

**Issue by kenjs** [Tomofiles/mavsdk_try#1]
I download the package, but i coundt fund Keys.js in package, so where i can get Keys.js ?
Thanks.

**Comment by Tomofiles** [comment]
Thank you for your comments.
Please get Keys.js by the following procedure.
You have to create a new file as "Keys.js".

1. Create a new file as "Keys.js" on "mavsdk_try/static".
2. Get the Access Tokens for Cesium ion by your Cesium ion accounts. Please check a following link for the Access Tokens details.
https://cesium.com/learn/cesiumjs-learn/cesiumjs-quickstart/
3. Write the following text in a created file.
`Cesium.Ion.defaultAccessToken = '\<Your Access Tokens\>';`

I'm sorry I couldn't prepare Keys.js.
I didn't include this file in git commit because it's sensitive.

**Comment by kenjs** [comment]
thanks
